# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r
r:
  - bioc-devel

cache: packages
bioc_required: true


env:
  - WARNINGS_ARE_ERRORS=false


r_packages:
  - ape
  - phangorn
  - ggplot2
  - vdiffr
  - magrittr
  - knitr
  - testthat

bioc_packages:
  - ggtree
  - BiocStyle

r_github_packages:
  - jimhester/covr


after_success:
  - Rscript -e 'library(covr);coveralls();codecov()'


notifications:
  email:
    on_success: change
    on_failure: always
