%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{R/Bioconductor package for visualization of phylogenetic networks in a ggplot2 framework.}
\documentclass{article}
\usepackage{amsmath}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{url}

<<style-knitr, eval=TRUE, echo=FALSE, results="asis">>=
BiocStyle::latex()
suppressPackageStartupMessages(library(ggtree))
suppressPackageStartupMessages(library(phangorn))
@


\begin{document}
<<setup, include=FALSE, cache=FALSE>>=
library(knitr)
@

\bioctitle{The \Biocpkg{ggnetworx} package for visualization of phylogenetic
networks in a ggplot2 framework. }

\author{Klaus Schliep \thanks{\email{klaus.schliep@gmail.com}}\\
University of Massachusetts Boston}

\maketitle

\tableofcontents

\section{Introduction}
\Biocpkg{ggnetworx} extends the \Biocpkg{ggtree} package to all plotting several
types of phylogentic networks. More specific it is possible to plot splits
graphs as in Splitstree and (directed, rooted) trees with reticulations.

\section{Splits graphs}
We first read the necessary libraries and read in a splits graph
<<>>=
library(phangorn)
library(ggnetworx)
fdir <- system.file("extdata/trees", package = "phangorn")
Nnet <- read.nexus.networx(file.path(fdir,"woodmouse.nxs"))
@

<<>>=
ggnetworx(Nnet) + geom_tiplab2()
@



\section{Summary}


\nocite{Schliep2011}
\nocite{Schliep2017}
\nocite{Paradis2004}
\nocite{Holland2004}
\nocite{Yu2017}
\nocite{Bryant2004}
\nocite{Huson2006}
\nocite{Cardona2008}
\nocite{Wickham2016}
% Paradis2018


\newpage
\bibliography{ggnetworx}

\newpage
<<sessionInfo>>=
sessionInfo()
@

\end{document}
