%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{R/Bioconductor package for visualization of phylogenetic networks in a ggplot2 framework.}
\documentclass{article}
\usepackage{amsmath}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{url}

<<style-knitr, eval=TRUE, echo=FALSE, results="asis">>=
BiocStyle::latex()
suppressPackageStartupMessages(library(ggtree))
suppressPackageStartupMessages(library(phangorn))
@

%%% TO DO (Later) %%%
% Change package name?
%
%%%%%%%%%%%%%%%%%%%%%

\begin{document}
<<setup, include=FALSE, cache=FALSE>>=
library(knitr)
@

\bioctitle{The \Biocpkg{ggnetworx} package for visualization of phylogenetic
networks in a ggplot2 framework. }

\author{Klaus Schliep \thanks{\email{klaus.schliep@gmail.com}}\\
University of Massachusetts Boston}

\maketitle

\tableofcontents

\newpage
\section{Introduction}
\Biocpkg{ggnetworx} extends the \Biocpkg{ggtree} \cite{Yu2017} package to allow
visualization of several types of phylogentic networks using the \CRANpkg{ggplot2} \cite{Wickham2016} syntax.
More specifically, \Biocpkg{ggnetworx} contains functions
to plot split networks (unrooted, undirected) and explicit networks (rooted, directed) with reticulations. It offers an alternative to the plot functions already available
in \CRANpkg{ape} and \CRANpkg{phangorn}.

\section{Getting Started}

Load the necessary libraries:
<<>>=
library(phangorn)
library(ggnetworx)
@

\section{Split Networks}

Split networks allow for the definition of non-compatible splits and are most often used to visualize consensus networks \cite{Holland2004} or neighbor-nets \cite{Bryant2004}. This can be done either by using the consensusNet or neighbor-net functions in \CRANpkg{phangorn} \cite{Schliep2011} or by importing nexus files from SplitsTree \cite{Huson2006}.

\subsection{Data Types}

\Biocpkg{ggnetworx} accepts the following three forms of input data for split networks:

Nexus files from SplitsTree \cite{Huson2006} read.nexus.networx \CRANpkg{phangorn}

\subsection{Plotting a Split Network}

Plot a split network:
<<>>=
## read in an example split network:
fdir <- system.file("extdata/trees", package = "phangorn")
Nnet <- read.nexus.networx(file.path(fdir,"woodmouse.nxs"))
## plot a split network:
ggsplitnet(Nnet) + geom_tiplab2()
@

Nodes can be annotated with $geom\_point$.
<<>>=
ggsplitnet(Nnet) + geom_point(aes(shape=isTip, color=isTip), size=3)
@


\section{Plotting Explicit Networks}

The function \Rfunction{ggevonet} plots explicit networks (phylogenetic trees with reticulations).
A recent addition to \CRANpkg{ape} \cite{Paradis2018}  made it possible
to read in trees in extended newick format \cite{Cardona2008}.

<<>>=
## read in an explicit network (example from Fig. 2 in Cardona et al. 2008):
z <- read.evonet(text =
         "((1,((2,(3,(4)Y#H1)g)e,(((Y#H1, 5)h,6)f)X#H2)c)a,((X#H2,7)d,8)b)r;")

## plot an explicit network:
ggevonet(z, aes(color=hybridEdge)) + geom_tiplab() + geom_nodelab()

ggevonet(z, aes(color=hybridEdge), "slanted") + geom_tiplab() + geom_nodelab()
@

\section{Summary}

The split network plots should take most of the functions compatible with unrooted
trees in ggtree. The explicit network plots are phylogram or slanted.
Not all options may work as intended yet.

\url{https://bioconductor.org/packages/devel/bioc/vignettes/ggtree/inst/doc/treeVisualization.html}



\nocite{Schliep2011}
\nocite{Schliep2017}
\nocite{Paradis2004}
% \nocite{Paradis2018}
\nocite{Holland2004}
\nocite{Yu2017}
\nocite{Bryant2004}
\nocite{Huson2006}
\nocite{Cardona2008}
\nocite{Wickham2016}


\newpage
\bibliography{ggnetworx}

\newpage
\appendix
\section{Session info}
<<sessionInfo>>=
sessionInfo()
@

\end{document}
