%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{R/Bioconductor package for visualization of phylogenetic networks in a ggplot2 framework.}
\documentclass{article}
\usepackage{amsmath}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{url}

<<style-knitr, eval=TRUE, echo=FALSE, results="asis">>=
BiocStyle::latex()
suppressPackageStartupMessages(library(ggtree))
suppressPackageStartupMessages(library(phangorn))
@


\begin{document}
<<setup, include=FALSE, cache=FALSE>>=
library(knitr)
@

\bioctitle{The \Biocpkg{ggnetworx} package for visualization of phylogenetic
networks in a ggplot2 framework. }

\author{Klaus Schliep \thanks{\email{klaus.schliep@gmail.com}}\\
University of Massachusetts Boston}

\maketitle

\tableofcontents

\newpage
\section{Introduction}
\Biocpkg{ggnetworx} extends the \Biocpkg{ggtree}\cite{Yu2017} package to allow
visualize several types of phylogentic networks using the \CRANpkg{ggplot2}
\cite{Wickham2016} syntax.
More specific \Biocpkg{ggnetworx} contains function
to plot (unrooted, undirected) splits graphs and (directed, rooted) trees with
reticulations. It offers an alternative to the plot functions already available
in \CRANpkg{ape} and \CRANpkg{phangorn}.

\section{Splits graphs}
Splits graph allow to non-compatible splits definition and are most often
used to visualize Consensus Networks \cite{Holland2004} or Neighbor-Nets
\cite{Bryant2004}. This can be either done using the consensusNet or neighbor-net
function in \CRANpkg{phangorn}\cite{Schliep2011} or by importing nexus files
from SplitsTree \cite{Huson2006}.

We first read the necessary libraries and read in a splits graph
<<>>=
library(phangorn)
library(ggnetworx)
fdir <- system.file("extdata/trees", package = "phangorn")
Nnet <- read.nexus.networx(file.path(fdir,"woodmouse.nxs"))
@

We can plot a splits graph using:
<<>>=
ggnetworx(Nnet) + geom_tiplab2()
@
Nodes can be annotated with $geom_point$.
<<>>=
ggnetworx(Nnet) + geom_point(aes(shape=isTip, color=isTip), size=3)
@


\section{Plotting reticulation networks}

The function \Rfunction{ggevonet} plots phylogenetic trees with reticulation.
A recent addition to the \CRANpkg{ape}\cite{Paradis2018}  made it possible
to read in trees in extended newick format \cite{Cardona2008}.

<<>>=
## from Fig. 2 in Cardona et al. 2008:
z <- read.evonet(text =
         "((1,((2,(3,(4)Y#H1)g)e,(((Y#H1, 5)h,6)f)X#H2)c)a,((X#H2,7)d,8)b)r;")
ggevonet(z, aes(color=hybridEdge)) + geom_tiplab() + geom_nodelab()

ggevonet(z, aes(color=hybridEdge), "slanted") + geom_tiplab() + geom_nodelab()
@

\section{Summary}

The splits graph should take most of the functions which go with unrooted
trees in ggtree. The reticulation graphs are phylogram or slanted.
Not all options may not work as intended yet.

\url{https://bioconductor.org/packages/devel/bioc/vignettes/ggtree/inst/doc/treeVisualization.html}



\nocite{Schliep2011}
\nocite{Schliep2017}
\nocite{Paradis2004}
% \nocite{Paradis2018}
\nocite{Holland2004}
\nocite{Yu2017}
\nocite{Bryant2004}
\nocite{Huson2006}
\nocite{Cardona2008}
\nocite{Wickham2016}


\newpage
\bibliography{ggnetworx}

\newpage
\appendix
\section{Session info}
<<sessionInfo>>=
sessionInfo()
@

\end{document}
